[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["iiTzArcur <zefanjaj@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python =  ">=3.13.2,<3.14"
homeassistant = "^2025.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
